### ISSUE TITLE
Problemas execução

### ISSUE THREAD

**Issue by gabriel-parizotto** [Thales1330/PSP#54]
Olá Thales,

Tive problema na execução do software, conforme imagem em anexo.

(versão do windows: 10 - 64 bits)
![Capturar](https://user-images.githubusercontent.com/67443981/85803572-d8f39c80-b71d-11ea-9191-ab2ddcfe83c1.JPG)

**Comment by Thales1330** [comment]
Verifique se o instalador da [(versão 32bits)](https://github.com/Thales1330/PSP/releases/download/2020w24a-beta/PSP-UFU_x86_32_VC.exe) apresenta o mesmo erro.

**Comment by gabriel-parizotto** [comment]
O instalador da versão 32 bits não apresentou esse problema! Consegui abrir o PSP-UFU.
Você teria o guia de utilização do software para fornecer? 
Desde  já agradeço pela ajuda.

**Comment by Thales1330** [comment]
Infelizmente ainda não tive tempo de criar o manual de utilização. Farei em breve.

**Comment by Thales1330** [comment]
Manual de usuário implementada! [Manual do PSP-UFU](https://thales1330.github.io/PSP/pt/docs/)
